from . import negative_inventory_policy
from . import res_company
from . import res_config_settings
from . import product_category
from . import product_template
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_scrap
from . import stock_quant
from . import negative_inventory_log
from . import negative_inventory_request
